### ISSUE TITLE
Question about HTTP vs HTTPS and Security...

### ISSUE THREAD

**Issue by JBatulevitz** [tableau/extension-single-checkbox-parameters#1]
Hello,

I was reading through code for your extension and I just noticed that in a few .trex files there was the following line of code used:

<manifest manifest-version="0.1" xmlns="http://www.tableau.com/xml/extension_manifest">

On the Tableau website, it mentioned that all URLs should utilize HTTPS for security reasons and I’m curious if you see any potential risks with having the HTTP version of this link used or if it should be modified to HTTPS.  Our analysts are really interested in your extension, but they’re concerned that this line of code could possibly have security implications so they asked me to reach out to you.  Any thoughts or feedback that you have is greatly appreciated.

Thank you.

![GitHubIssue](https://user-images.githubusercontent.com/51452724/59538909-4d6bec80-8ec9-11e9-93df-8e62704c0c2e.jpg)

**Comment by tagyoureit** [comment]
This is just a namespace and not an actual URL that is used to retrieve information.  You can see [StackOverflow](https://stackoverflow.com/questions/30707609/xml-namespace-uri-with-https) for more in depth info.  Essentially, this isn't used for any data communication just identification.
