### ISSUE TITLE
Extension single check boxes - Your browser does not suport extension in mobile (OS)

### ISSUE THREAD

**Issue by AdaJimenez** [tableau/extension-single-checkbox-parameters#3]
Hello,

I am implementing the extension on my dashboard and everything works fine for desktop but when creating the layer for mobile OS (iphone x), instead of seeing the check boxes, I see a legend that says: Your browser does not support extension. For mobile Android (example: Galaxy), everything works fine (Attach image).

Would you be so kind to tell us if you have any comments on how to solve this issue?

Thanks in advance

Iphone
![image](https://user-images.githubusercontent.com/63795627/79471303-7456eb80-7fd0-11ea-8b1f-7523d8606989.png)

**Comment by tagyoureit** [comment]
Can you please let me know what browser you are using?  And out of curiosity, have you tried different browsers (eg chrome, safari).

**Comment by AdaJimenez** [comment]
Hi ,

The issue is presented only in Tableau mobile app and only for iphone. In Chrome, exlorer, edge and safari browsers in desktop format everything appears correctly.

Regards,

**Comment by tagyoureit** [comment]
I was able to replicate the issue and submitted a bug internally.  I'll update this thread when I get some updates.

**Comment by tagyoureit** [comment]
This is now fixed.  We made some changes on the backend hosting code so there isn't anything you'll need to change.  Closing this for now but feel free to re-open if you still have issues.
